# Continuous deployment for Angular
name: Angular GitHub CD

on:
  # Triggers the workflow on push to main branch
  push:
    branches: [ main ]
jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     
     steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 18.19.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.19.1

      - name: Setup
        run: npm ci

      - name: Lint
        run:
          npm run lint

      - name: Unit Test with Karma
        run:
          npm run test:ci

      - name: Deploy
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          npm run deploy
